name: CI

on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.operating-system }}
    env:
        DOTNET_MULTILEVEL_LOOKUP: false      #use our version which we install ourself... see https://github.com/actions/setup-dotnet#environment-variables-to-use-with-dotnet
        DOTNET_NOLOGO: true                  #speed up things
        DOTNET_CLI_TELEMETRY_OPTOUT: true    #do not send telemetry to Microsoft
    strategy:
      matrix:
        operating-system: [windows-latest] #ubuntu-latest, macOS-latest
    #runs-on: [windows-latest]
       
    steps:

      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup dotnet env
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: '5.0.x' # SDK Version to use.  3.1.x uses the latest version of the 3.1 channel


      - name: Build projects
        run: dotnet build --configuration Release cloudBackup.sln


      - name: Run unit-tests
        run: dotnet test --verbosity normal


      - name: Publish for Win-x64 as SingleFile
        run: dotnet publish --configuration Release --runtime win-x64 --output cloudBackupUI/bin/Release/net5.0-windows/win-x64/publish_singlefile/ /p:PublishSingleFile=true /p:PublishTrimmed=true cloudBackupUI/cloudBackupUI.csproj


      - name: Upload artifact for Win-x64 as SingleFile
        uses: actions/upload-artifact@v3
        with:
            name: RemoteIncrediBuild_Release_Win-x64_SingleFile
            path: cloudBackupUI/bin/Release/net5.0-windows/win-x64/publish_singlefile/

      # With single file you cannot edit appsettings.json... or only in the temp folder... so we create it also not as single file
      - name: Publish for Win-x64
        run: dotnet publish --configuration Release --runtime win-x64 /p:PublishTrimmed=true cloudBackupUI/cloudBackupUI.csproj


      - name: Upload artifact for Win-x64
        uses: actions/upload-artifact@v3
        with:
            name: RemoteIncrediBuild_Release_Win-x64
            path: cloudBackupUI/bin/Release/net5.0-windows/win-x64/publish/