name: CI

on: [push]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.operating-system }}
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        operating-system: [windows-latest] #ubuntu-latest, macOS-latest
    #runs-on: [windows-latest]
       
    steps:

      - name: Checkout
        uses: actions/checkout@master


      - name: Setup dotnet env
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.100' # SDK Version to use.


      - name: build project
        run: dotnet build --configuration Release cloudBackup.sln


      - name: Run tests
        run: dotnet test --verbosity normal


      - name: Publish
        run: dotnet publish --configuration Release --runtime win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true cloudBackupUI/cloudBackupUI.csproj
      #- run: dotnet publish --configuration Release --self-contained=true --runtime win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true src/RemoteIncrediBuild/RemoteIncrediBuild.csproj


      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
            name: RemoteIncrediBuild_Release_x64
            path: cloudBackupUI\bin\Release\netcoreapp3.1\win-x64\publish\